export const queryKeys = {
  clusters: ['clusters'] as const,
  namespaces: ['namespaces'] as const,
  overview: ['overview'] as const,
  alertSummary: ['alertSummary'] as const,
  alerts: ['alerts'] as const,
  events: (namespace: string) => ['events', namespace] as const,
  pods: (namespace: string) => ['pods', namespace] as const,
  podsMetrics: ['pods-metrics'] as const,
  deployments: (namespace: string) => ['deployments', namespace] as const,
  services: (namespace: string) => ['services', namespace] as const,
  ingresses: (namespace: string) => ['ingresses', namespace] as const,
  configMaps: (namespace: string) => ['configmaps', namespace] as const,
  secrets: (namespace: string) => ['secrets', namespace] as const,
  observationSummary: ['observation-summary'] as const,
  observationCpuTrend: (range: string) => ['observation-cpu-trend', range] as const,
  observationMemoryTrend: (range: string) => ['observation-memory-trend', range] as const,
  observationRestartTrend: (range: string) => ['observation-restart-trend', range] as const,
};
